stages:
  - build
  - pages

build:
  stage: build
  image: node:16.16.0-alpine3.16
  script:
    - npm ci
    - npm run build
  cache:
    paths:
      - dist/

pages:
  stage: pages
  script:
    - mv public .public
    - mkdir public
    - cp -r dist/* public
  artifacts:
    paths:
      - public
  cache:
    policy: pull
    paths:
      - dist/
