stages:
  - build
#  - pages

build:
  stage: build
  image: node:16.16.0-alpine3.16
  script:
    - |
      [ ! -d 'node_modules' ] && npm ci
    - npm run build
  cache:
    key:
      files:
        # - yarn.lock
        - package-lock.json
    paths:
      - node_modules/
#  cache:
#    paths:
#      - dist/

#pages:
#  stage: pages
#  script:
#    - mv public .public
#    - mkdir public
#    - cp -r dist/* public
#  artifacts:
#    paths:
#      - public
#  cache:
#    policy: pull
#    paths:
#      - dist/
